"""Operations suite. Revision ID: q9a0b1c2d345 Revises: p8f9a0b1c234"""
from alembic import op
import sqlalchemy as sa
revision='q9a0b1c2d345'; down_revision='p8f9a0b1c234'; branch_labels=None; depends_on=None

def upgrade():
 op.create_table('supplier_payment',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('supplier_id',sa.Integer(),sa.ForeignKey('supplier.id'),nullable=False),sa.Column('amount',sa.Numeric(12,2),nullable=False),sa.Column('payment_date',sa.Date(),nullable=False),sa.Column('method',sa.String(30)),sa.Column('reference',sa.String(100)),sa.Column('notes',sa.Text()),sa.Column('created_by',sa.Integer(),sa.ForeignKey('user.id')),sa.Column('created_at',sa.DateTime(),server_default=sa.func.now(),nullable=False)); op.create_index('ix_supplier_payment_supplier_id','supplier_payment',['supplier_id']); op.create_index('ix_supplier_payment_payment_date','supplier_payment',['payment_date'])
 op.create_table('expense',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('expense_date',sa.Date(),nullable=False),sa.Column('category',sa.String(50),nullable=False),sa.Column('amount',sa.Numeric(12,2),nullable=False),sa.Column('repair_id',sa.Integer(),sa.ForeignKey('repair_order.id')),sa.Column('description',sa.String(255),nullable=False),sa.Column('payment_method',sa.String(30)),sa.Column('reference',sa.String(100)),sa.Column('created_by',sa.Integer(),sa.ForeignKey('user.id')),sa.Column('created_at',sa.DateTime(),server_default=sa.func.now(),nullable=False)); op.create_index('ix_expense_expense_date','expense',['expense_date']); op.create_index('ix_expense_category','expense',['category']); op.create_index('ix_expense_repair_id','expense',['repair_id'])
 op.create_table('stock_allocation',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('part_id',sa.Integer(),sa.ForeignKey('part.id'),nullable=False),sa.Column('repair_id',sa.Integer(),sa.ForeignKey('repair_order.id'),nullable=False),sa.Column('technician_id',sa.Integer(),sa.ForeignKey('user.id')),sa.Column('quantity',sa.Numeric(12,2),nullable=False),sa.Column('status',sa.String(30),nullable=False),sa.Column('notes',sa.Text()),sa.Column('created_by',sa.Integer(),sa.ForeignKey('user.id')),sa.Column('created_at',sa.DateTime(),server_default=sa.func.now(),nullable=False),sa.Column('updated_at',sa.DateTime(),server_default=sa.func.now(),nullable=False)); op.create_index('ix_stock_allocation_part_id','stock_allocation',['part_id']); op.create_index('ix_stock_allocation_repair_id','stock_allocation',['repair_id']); op.create_index('ix_stock_allocation_technician_id','stock_allocation',['technician_id']); op.create_index('ix_stock_allocation_status','stock_allocation',['status'])
 op.create_table('audit_event',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('user_id',sa.Integer(),sa.ForeignKey('user.id')),sa.Column('action',sa.String(80),nullable=False),sa.Column('entity_type',sa.String(50),nullable=False),sa.Column('entity_id',sa.Integer()),sa.Column('details',sa.Text()),sa.Column('created_at',sa.DateTime(),server_default=sa.func.now(),nullable=False)); op.create_index('ix_audit_event_user_id','audit_event',['user_id']); op.create_index('ix_audit_event_action','audit_event',['action']); op.create_index('ix_audit_event_entity_type','audit_event',['entity_type']); op.create_index('ix_audit_event_entity_id','audit_event',['entity_id']); op.create_index('ix_audit_event_created_at','audit_event',['created_at'])

def downgrade():
 for t in ['audit_event','stock_allocation','expense','supplier_payment']: op.drop_table(t)
